name: Fetch project status values
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
    default: ${{ github.token }}
  project-number:
    description: Number of your project. It's available in your project's URL
    required: true
outputs:
  result:
    description: |
      The project description, with possible status values
      It's a JSON document of the form:
      {
        "id": "<project ID>",
        "statusField": {
            "id": "<field ID>",
            "name": "Status",
            "options": [
                { "id": "<option ID 1>", "name": "Inbox" },
                { "id": "<option ID 2>", "name": "Backlog" },
                { "id": "<option ID 3>", "name": "To Refine" },
                { "id": "<option ID 4>", "name": "Ready to dev" },
                { "id": "<option ID 5>", "name": "In Progress" },
                { "id": "<option ID 6>", "name": "Done "}
            ]
        }
      }
    value: ${{ toJSON(fromJSON(steps.get-project-data.outputs.data).organization.projectV2) }}
runs:
  using: composite
  steps:
    - name: Get project data
      id: get-project-data
      uses: octokit/graphql-action@v2.x
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        query: |
          query($org: String!, $number: Int!) {
            organization(login: $org){
              projectV2(number: $number) {
                id
                statusField: field(name:"Status") {
                  ... on ProjectV2SingleSelectField {
                    id
                    name
                    options {
                      id
                      name
                    }
                  }
                }
              }
            }
          }
        variables: |
          org: ${{ github.event.organization.login }}
          number: ${{ inputs.project-number }}
