name: Fetch project status values
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
    default: ${{ github.token }}
  project-number:
    description: Number of your project. It's available in your project's URL
    required: true
outputs:
  result:
    description: |
      The project description, with possible status values
      It's a JSON document of the form:
      {
        "id": "<project ID>",
        "statusField": {
            "id": "<field ID>",
            "name": "Status",
            "options": [
                { "id": "<option ID 1>", "name": "Inbox" },
                { "id": "<option ID 2>", "name": "Backlog" },
                { "id": "<option ID 3>", "name": "To Refine" },
                { "id": "<option ID 4>", "name": "Ready to dev" },
                { "id": "<option ID 5>", "name": "In Progress" },
                { "id": "<option ID 6>", "name": "Done "}
            ]
        }
      }
    value: ${{ steps.get-project-data.outputs.result }}
runs:
  using: composite
  steps:
    - name: Get project data
      id: get-project-data
      uses: actions/github-script@v6
      env:
        PROJECT_NUMBER: ${{ inputs.project-number }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const query = `query($org: String!, $number: Int!) {
            organization(login: $org){
              projectV2(number: $number) {
                id
                statusField: field(name:"Status") {
                  ... on ProjectV2SingleSelectField {
                    id
                    name
                    options {
                      id
                      name
                    }
                  }
                }
              }
            }
          }`;
          const variables = {
            org: context.payload.organization.login,
            number: parseInt(process.env.PROJECT_NUMBER, 10)
          };
          return (await github.graphql(query, variables)).organization.projectV2;
