# This GitHub Action assigns its author to all new PRs
#
#
# This action is triggered when
# - a new PR is opened
# - or  PR is reopened
# It does nothing if
# - the PR has already some assignees
# - or the PR author is a bot (type === "Bot")
# Else, it assigns its author to the PR


name: Assign authors to PRs

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.0.1
