# This GitHub Action opens PRs to automate the gitflow.
#
#
# This action triggers when a commit is done on `prod` or `beta`.
# It creates a new branch with this commit.
# It then opens a PR to merge the new commit in the appropriate other main branches:
#   - if the commit is on `prod`, the PR targets `beta`
#   - if the commit is on `beta`, the PR targets `dev`


name: Gitflow

on:
  push:
    branches:
        - prod
        - beta 

jobs:
  gitflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create branch
        # `ref_name` is the current branch name  
        # `sha` is the latest commit sha
        run: git checkout -b gitflow/${{ github.ref_name }}-${{ github.sha }}

      - name: Push branch
        run: git push origin gitflow/${{ github.ref_name }}-${{ github.sha }}

      - run: |
          gh pr create \
          --head gitflow/${{ github.ref_name }}-${{ github.sha }} \
          --base ${{ github.ref_name == 'prod' && 'beta' || 'dev' }} \
          --title "chore(gitflow): Merge ${{ github.ref_name }}'s commit ${{ github.sha }}" \
          --body ":warning: This PR has been automatically created." \
          --assignee "@me" \
          --reviewer ${{ github.event.pusher.username }} \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          gh pr merge \
          --auto \
          --merge \
          --delete-branch \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
