# This GitHub Action purges old migration scripts (files in packages/backend/zscripts/migrations).
#
#
# This action triggers once a month.
# It executes the following steps:
# - create a new branch
# - delete old scripts
# - commit
# - create a PR
# - auto-merge it


name: Purge migration scripts

on:
  workflow_dispatch:

env:
  BASE: master
  BRANCH_NAME: purge-migrations-scripts/${{ github.run_id }}
  PURGE_DAYS: 61

jobs:
  purge_migration_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Generate an access token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.AUTHENTICATOR_APP_ID }}
          private_key: ${{ secrets.AUTHENTICATOR_APP_PEM }}

      - uses: actions/checkout@v4
        with:
            ref: ${{ env.BASE }}

      - name: Delete old files
        run: |
          limit=$( date -d "$PURGE_DAYS days ago" +%Y%m%dT%H%M%SZ- )
          pattern="^[0-9]{8}T[0-9]{6}Z-"
          for file in *; do
            if [[ $file =~ $pattern && $file < $limit ]]; then
              rm $file
            fi
          done
        working-directory: ${{ github.workspace }}/packages/backend/zscripts/migrations

      - name: Commit in new branch
        id: commit-in-branch
        uses: ./.github/reusable-actions/commit-in-branch
        with:
          branch-name: ${{ env.BRANCH_NAME }}
          commit-message: |
            Purge migration
            scripts older than ${{ env.PURGE_DAYS }} days
            escaping $( echo special ) metacharacters
            for the shell...

      - name: Create pull request
        if: ${{ steps.commit-in-branch.outputs.created == 'true' }}
        uses: ./.github/reusable-actions/create-pull-request
        with:
          head: ${{ env.BRANCH_NAME }}
          base: ${{ env.BASE }}
          title: "chore(migrations): purge old migration scripts"
          body: "Purging migrations scripts older than ${{ env.PURGE_DAYS }} days from `packages/backend/zscripts/migrations`"
          reviewers: '["LucVidal360"]'
          auto-merge: true
          github-token: ${{ steps.generate_token.outputs.token }}
