# This GitHub Action purges old migration scripts (files in packages/backend/zscripts/migrations).
#
#
# This action triggers once a month.
# It executes the following steps:
# - create a new branch
# - delete old scripts
# - commit
# - create a PR
# - auto-merge it


name: Purge migration scripts

on:
  workflow_dispatch:

env:
  BASE: master
  BRANCH_NAME: purge-migrations-scripts/${{ github.run_id }}
  PURGE_DAYS: ${{ 61 }}
  SCRIPT_PATTERN: ^[0-9]{8}T[0-9]{6}Z-

jobs:
  purge_migration_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Generate an access token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.AUTHENTICATOR_APP_ID }}
          private_key: ${{ secrets.AUTHENTICATOR_APP_PEM }}

      - uses: actions/checkout@v4
        with:
            ref: ${{ env.BASE }}

      - name: Delete old files
        run: |
          limit=$( date -d "$PURGE_DAYS days ago" +%Y%m%dT%H%M%SZ- )
          for file in *; do
            if [[ $file =~ $SCRIPT_PATTERN && $file < $limit ]]; then
              rm $file
            fi
          done
        working-directory: ${{ github.workspace }}/packages/backend/zscripts/migrations

      - name: Commit in new branch
        id: commit-in-branch
        uses: ./.github/reusable-actions/commit-in-branch
        with:
          branch-name: ${{ env.BRANCH_NAME }}

      - name: Open Pull Request
        if: ${{ steps.commit-in-branch.outputs.created == 'true' }}
        run: |
          GH_DEBUG=api gh pr create \
            --head $BRANCH_NAME \
            --base $BASE \
            --label bot🤖 \
            --reviewer 360Learning/developer-experience \
            --title "chore(migrations): purge old migration scripts" \
            --body ":warning: This PR has been automatically created."
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Approve PR
        if: ${{ steps.commit-in-branch.outputs.created == 'true' }}
        run: gh pr review --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Activate automerge for Pull Request
        if: ${{ steps.commit-in-branch.outputs.created == 'true' }}
        run: gh pr merge --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
