name: Remove labels on close

on:
  issues:
    types:
      - closed

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const USELESS_LABELS_WHEN_ISSUE_IS_CLOSED = [
              "codeReview",
              "maturation",
              "review",
              "waitingForDev"
            ];

            for (const uselessLabel of USELESS_LABELS_WHEN_ISSUE_IS_CLOSED) {
              if(! context.payload.issue.labels.some(({ name }) => name === uselessLabel)) { continue; }

              github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                name: uselessLabel
              })
            }

