name: Remove labels on close

on:
  issues:
    types:
      - closed

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            codeReview
            maturation
            review
            waitingForDev

