name: Remove labels on close

on:
  issues:
    types:
      - closed

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/scripts/removeLabelsOnClose.js')
            console.log(script({ github, context }))

