# This GitHub Action purges old migration scripts (files in packages/backend/zscripts/migrations).
#
#
# This action triggers once a month.
# It executes the following steps:
# - create a new branch
# - delete old scripts
# - commit
# - create a PR
# - auto-merge it


name: Tries to fetch teams

on:
  workflow_dispatch:

env:
  BASE: master

jobs:
  purge_migration_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Generate an access token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.AUTHENTICATOR_APP_ID }}
          private_key: ${{ secrets.AUTHENTICATOR_APP_PEM }}
          permissions: '{"members":"read"}'

      - name: lookup team 1
        run: |
          echo "::group::lookup1"
          gh api graphql -f query='{organization(login:"360Learning"){team(slug:"developer-experience"){slug,id}}}'
          echo ""
          echo "::endgroup::"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: lookup team 2
        run: |
          echo "::group::lookup2"
          gh api graphql -f query='{organization(login:"360Learning"){team(slug:"developer-experience"){slug,id}}}'
          echo ""
          echo "::endgroup::"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
